-- Persist closed MT5 robot positions for owner-scoped performance analysis.
--
-- The worker may only write through the service-role API. Browser sessions are
-- read-only and remain protected by RLS. Account identifiers are pseudonymous
-- hashes generated by the worker; the MT5 login is never stored here.

BEGIN;

DO $migration$
BEGIN
  IF to_regclass('public.users') IS NULL THEN
    RAISE EXCEPTION
      'users table is missing; apply the canonical schema before trade intelligence'
      USING ERRCODE = '55000';
  END IF;
END
$migration$;

CREATE TABLE IF NOT EXISTS public.robot_trade_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  account_ref TEXT NOT NULL,
  broker_position_id TEXT NOT NULL,
  strategy TEXT NOT NULL,
  market_type TEXT NOT NULL,
  symbol TEXT NOT NULL,
  side TEXT NOT NULL,
  volume NUMERIC NOT NULL,
  entry_time TIMESTAMPTZ NOT NULL,
  exit_time TIMESTAMPTZ NOT NULL,
  entry_price NUMERIC NOT NULL,
  exit_price NUMERIC NOT NULL,
  initial_stop_loss NUMERIC,
  initial_take_profit NUMERIC,
  gross_profit NUMERIC NOT NULL,
  commission NUMERIC NOT NULL DEFAULT 0,
  swap NUMERIC NOT NULL DEFAULT 0,
  fee NUMERIC NOT NULL DEFAULT 0,
  net_profit NUMERIC GENERATED ALWAYS AS (
    gross_profit + commission + swap + fee
  ) STORED,
  duration_seconds INTEGER NOT NULL,
  exit_reason TEXT NOT NULL,
  entry_comment TEXT,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT robot_trade_history_owner_position_unique
    UNIQUE (user_id, account_ref, broker_position_id),
  CONSTRAINT robot_trade_history_account_ref_valid
    CHECK (account_ref ~ '^[0-9a-f]{24}$'),
  CONSTRAINT robot_trade_history_position_id_valid
    CHECK (broker_position_id ~ '^[1-9][0-9]{0,31}$'),
  CONSTRAINT robot_trade_history_strategy_valid
    CHECK (
      char_length(strategy) BETWEEN 3 AND 64
      AND strategy ~ '^[a-z][a-z0-9_-]{2,63}$'
    ),
  CONSTRAINT robot_trade_history_market_type_valid
    CHECK (market_type IN ('crypto', 'forex')),
  CONSTRAINT robot_trade_history_symbol_valid
    CHECK (
      char_length(symbol) BETWEEN 2 AND 32
      AND symbol ~ '^[A-Z0-9][A-Z0-9./_#-]{1,31}$'
    ),
  CONSTRAINT robot_trade_history_side_valid
    CHECK (side IN ('buy', 'sell')),
  CONSTRAINT robot_trade_history_volume_valid
    CHECK (volume > 0 AND volume <= 1000000),
  CONSTRAINT robot_trade_history_time_valid
    CHECK (exit_time >= entry_time),
  CONSTRAINT robot_trade_history_price_valid
    CHECK (entry_price > 0 AND exit_price > 0),
  CONSTRAINT robot_trade_history_stop_valid
    CHECK (initial_stop_loss IS NULL OR initial_stop_loss > 0),
  CONSTRAINT robot_trade_history_target_valid
    CHECK (initial_take_profit IS NULL OR initial_take_profit > 0),
  CONSTRAINT robot_trade_history_duration_valid
    CHECK (duration_seconds >= 0),
  CONSTRAINT robot_trade_history_reason_valid
    CHECK (
      char_length(exit_reason) BETWEEN 2 AND 64
      AND exit_reason ~ '^[a-z][a-z0-9_-]{1,63}$'
    ),
  CONSTRAINT robot_trade_history_comment_valid
    CHECK (
      entry_comment IS NULL
      OR (
        char_length(entry_comment) BETWEEN 1 AND 64
        AND entry_comment !~ '[[:cntrl:]]'
      )
    )
);

CREATE INDEX IF NOT EXISTS robot_trade_history_owner_exit_idx
  ON public.robot_trade_history (user_id, exit_time DESC);

CREATE INDEX IF NOT EXISTS robot_trade_history_owner_strategy_idx
  ON public.robot_trade_history (user_id, strategy, exit_time DESC);

CREATE INDEX IF NOT EXISTS robot_trade_history_owner_symbol_idx
  ON public.robot_trade_history (user_id, symbol, exit_time DESC);

ALTER TABLE public.robot_trade_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own robot trade history"
  ON public.robot_trade_history;

CREATE POLICY "Users can view own robot trade history"
ON public.robot_trade_history
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

REVOKE ALL ON TABLE public.robot_trade_history FROM PUBLIC;
REVOKE ALL ON TABLE public.robot_trade_history FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
  ON TABLE public.robot_trade_history FROM authenticated;
GRANT SELECT ON TABLE public.robot_trade_history TO authenticated;
GRANT ALL ON TABLE public.robot_trade_history TO service_role;

COMMIT;
